data_config:
  data_info:
   RNA:
     file_path: "data/raw/mini/bulk/rna_sample_data.parquet"
     is_single_cell: false
     translate_direction: "from"
     data_type: "NUMERIC"
   METH:
     file_path: "data/raw/mini/bulk/meth_sample_data.parquet"
     is_single_cell: false
     translate_direction: "to"
     data_type: "NUMERIC"
