paired_translation: False
data_config:
  data_info:
   RNA:
     file_path: "data/raw/mini/bulk/rna_sample_data.csv"
     is_single_cell: false
     translate_direction: "from"
   IMG:
     file_path: "data/raw/mini/img2/"
     is_single_cell: false
     translate_direction: "to"
     data_type: "IMG"
     extra_anno_file: "data/raw/mini/tcga_mappings2.txt"
   CLIN:
     file_path: "data/raw/mini/bulk/clinical_sample_data.tsv"
     data_type: "ANNOTATION"
