data_config:
  data_info:
   RNA:
     file_path: "data/raw/mini/bulk/rna_sample_data.csv"
     is_single_cell: false
     translate_direction: "from"
   IMG:
     file_path: "data/raw/mini/img/"
     is_single_cell: false
     translate_direction: "to"
     data_type: "IMG"
   MAPPING:
     file_path: "data/raw/mini/tcga_mappings.txt"
     data_type: "ANNOTATION"
