data_config:
  data_info:
    RNA:
      file_path: "data/raw/combined_rnaseq_formatted.parquet"
    METHYLATION:
      file_path: "data/raw/combined_meth_formatted.parquet"
    CLINICAL:
      file_path: "data/raw/combined_clin_formatted.parquet"
      data_type: "ANNOTATION"
