data_config:
  data_info:
    RNA:
      file_path: "data/raw/mini/bulk/rna_sample_data.csv"
      sep: ","
    METHYLATION:
      file_path: "data/raw/mini/bulk/meth_sample_data.tsv"
      sep: "\t"
    CLINICAL:
      file_path: "data/raw/mini/bulk/clinical_sample_data.parquet"
      data_type: "ANNOTATION"
