data_config:
 data_info:
   RNA:
     file_path: "data/raw/mini/single_cell/rna_sample_data.h5ad"
     is_single_cell: true
     min_cells: 0.01
     min_genes: 0.01
     is_X: true
   METH:
     file_path: "data/raw/mini/single_cell/meth_sample_data.h5ad"
     is_single_cell: true
     min_cells: 0.01
