
data_config:
 data_info:
   RNA:
     # file_path: "data/raw/mini/single_cell/rna_sample_data.h5ad"
     file_path: "data/raw/Sc-1-mini.h5ad"
     is_single_cell: true
     min_cells: 0.01
     min_genes: 0.01
     is_X: true
     translate_direction: "from"
   METH:
     # file_path: "data/raw/mini/single_cell/meth_sample_data.h5ad"

     file_path: "data/raw/Sc-2-mini.h5ad"
     is_single_cell: true
     min_cells: 0.01
     translate_direction: "to"
